# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\vieta\OneDrive\Documents\mangareader\keyboard_widget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_KBWidget(object):
    def setupUi(self, KBWidget):
        KBWidget.setObjectName(_fromUtf8("KBWidget"))
        KBWidget.resize(858, 300)
        self.tableWidget = QtGui.QTableWidget(KBWidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 1046, 277))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(14)
        self.tableWidget.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 11, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 13, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(60)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.verticalHeader().setDefaultSectionSize(45)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)

        self.retranslateUi(KBWidget)
        QtCore.QMetaObject.connectSlotsByName(KBWidget)

    def retranslateUi(self, KBWidget):
        KBWidget.setWindowTitle(_translate("KBWidget", "Form", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("KBWidget", "~ `", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("KBWidget", "! 1", None))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("KBWidget", "@ 2", None))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("KBWidget", "# 3", None))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("KBWidget", "$ 4", None))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("KBWidget", "% 5", None))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("KBWidget", "^ 6", None))
        item = self.tableWidget.item(0, 7)
        item.setText(_translate("KBWidget", "& 7", None))
        item = self.tableWidget.item(0, 8)
        item.setText(_translate("KBWidget", "* 8", None))
        item = self.tableWidget.item(0, 9)
        item.setText(_translate("KBWidget", "( 9", None))
        item = self.tableWidget.item(0, 10)
        item.setText(_translate("KBWidget", ") 0", None))
        item = self.tableWidget.item(0, 11)
        item.setText(_translate("KBWidget", "- _", None))
        item = self.tableWidget.item(0, 12)
        item.setText(_translate("KBWidget", "+ =", None))
        item = self.tableWidget.item(0, 13)
        item.setText(_translate("KBWidget", "BkSp", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("KBWidget", "Tab", None))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("KBWidget", "Q", None))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("KBWidget", "W", None))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("KBWidget", "E", None))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("KBWidget", "R", None))
        item = self.tableWidget.item(1, 5)
        item.setText(_translate("KBWidget", "T", None))
        item = self.tableWidget.item(1, 6)
        item.setText(_translate("KBWidget", "Y", None))
        item = self.tableWidget.item(1, 7)
        item.setText(_translate("KBWidget", "U", None))
        item = self.tableWidget.item(1, 8)
        item.setText(_translate("KBWidget", "I", None))
        item = self.tableWidget.item(1, 9)
        item.setText(_translate("KBWidget", "O", None))
        item = self.tableWidget.item(1, 10)
        item.setText(_translate("KBWidget", "P", None))
        item = self.tableWidget.item(1, 11)
        item.setText(_translate("KBWidget", "{ [", None))
        item = self.tableWidget.item(1, 12)
        item.setText(_translate("KBWidget", "} ]", None))
        item = self.tableWidget.item(1, 13)
        item.setText(_translate("KBWidget", "| \\", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("KBWidget", "Caps Lock", None))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("KBWidget", "A", None))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("KBWidget", "S", None))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("KBWidget", "D", None))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("KBWidget", "F", None))
        item = self.tableWidget.item(2, 5)
        item.setText(_translate("KBWidget", "G", None))
        item = self.tableWidget.item(2, 6)
        item.setText(_translate("KBWidget", "H", None))
        item = self.tableWidget.item(2, 7)
        item.setText(_translate("KBWidget", "J", None))
        item = self.tableWidget.item(2, 8)
        item.setText(_translate("KBWidget", "K", None))
        item = self.tableWidget.item(2, 9)
        item.setText(_translate("KBWidget", "L", None))
        item = self.tableWidget.item(2, 10)
        item.setText(_translate("KBWidget", ": ;", None))
        item = self.tableWidget.item(2, 11)
        item.setText(_translate("KBWidget", "\" \'", None))
        item = self.tableWidget.item(2, 12)
        item.setText(_translate("KBWidget", "Enter", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("KBWidget", "Shift", None))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("KBWidget", "Z", None))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("KBWidget", "X", None))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("KBWidget", "C", None))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("KBWidget", "V", None))
        item = self.tableWidget.item(3, 5)
        item.setText(_translate("KBWidget", "B", None))
        item = self.tableWidget.item(3, 6)
        item.setText(_translate("KBWidget", "N", None))
        item = self.tableWidget.item(3, 7)
        item.setText(_translate("KBWidget", "M", None))
        item = self.tableWidget.item(3, 8)
        item.setText(_translate("KBWidget", "< ,", None))
        item = self.tableWidget.item(3, 9)
        item.setText(_translate("KBWidget", "> .", None))
        item = self.tableWidget.item(3, 10)
        item.setText(_translate("KBWidget", "? /", None))
        item = self.tableWidget.item(3, 11)
        item.setText(_translate("KBWidget", "Shift", None))
        item = self.tableWidget.item(3, 12)
        item.setText(_translate("KBWidget", "Up", None))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("KBWidget", "Ctrl", None))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("KBWidget", "Fn", None))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("KBWidget", "Win", None))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("KBWidget", "Alt", None))
        item = self.tableWidget.item(4, 6)
        item.setText(_translate("KBWidget", "Space", None))
        item = self.tableWidget.item(4, 9)
        item.setText(_translate("KBWidget", "Alt", None))
        item = self.tableWidget.item(4, 10)
        item.setText(_translate("KBWidget", "Ctrl", None))
        item = self.tableWidget.item(4, 11)
        item.setText(_translate("KBWidget", "Left", None))
        item = self.tableWidget.item(4, 12)
        item.setText(_translate("KBWidget", "Down", None))
        item = self.tableWidget.item(4, 13)
        item.setText(_translate("KBWidget", "Right", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

